/*
 * config.h
 *
 * Created: 8/16/2020 6:03:34 PM
 *  Author: connor
 */ 


#ifndef CONFIG_H_
#define CONFIG_H_


enum pcba_id {
	PCBA_ID_SENSOR_BOARD_CG,
	PCBA_ID_SENSOR_BOARD_FRONT,
	PCBA_ID_SENSOR_BOARD_REAR,
	PCBA_ID_SENSOR_BOARD_FL_UPRIGHT,
	PCBA_ID_SENSOR_BOARD_FR_UPRIGHT,
	PCBA_ID_SENSOR_BOARD_RL_UPRIGHT,
	PCBA_ID_SENSOR_BOARD_RR_UPRIGHT,
	
	PCBA_ID_COUNT,
	PCBA_ID_INVALID
};

#ifndef PCBA_ID
#define PCBA_ID PCBA_ID_SENSOR_BOARD_FRONT
#endif


#endif /* CONFIG_H_ */