/*
 * config.h
 *
 * Created: 8/16/2020 6:03:34 PM
 *  Author: connor
 */ 


#ifndef CONFIG_H_
#define CONFIG_H_


#define PCBA_ID_SENSOR_BOARD_CG			1U
#define PCBA_ID_SENSOR_BOARD_FRONT		2U
#define PCBA_ID_SENSOR_BOARD_REAR		3U
#define PCBA_ID_SENSOR_BOARD_FL_UPRIGHT	4U
#define PCBA_ID_SENSOR_BOARD_FR_UPRIGHT	5U
#define PCBA_ID_SENSOR_BOARD_RL_UPRIGHT	6U
#define PCBA_ID_SENSOR_BOARD_RR_UPRIGHT	7U

#define GENERAL_PURPOSE (PCBA_ID == PCBA_ID_SENSOR_BOARD_CG) || (PCBA_ID == PCBA_ID_SENSOR_BOARD_FRONT) || (PCBA_ID == PCBA_ID_SENSOR_BOARD_REAR)
#define UPRIGHT (PCBA_ID == PCBA_ID_SENSOR_BOARD_FL_UPRIGHT) || (PCBA_ID == PCBA_ID_SENSOR_BOARD_FR_UPRIGHT) || (PCBA_ID == PCBA_ID_SENSOR_BOARD_RL_UPRIGHT) || (PCBA_ID == PCBA_ID_SENSOR_BOARD_RR_UPRIGHT)

#endif /* CONFIG_H_ */