#pragma once

enum drv_adc_channel {
	// Read analog sensor 1-6
	DRV_ADC_CHANNEL_SENSE1,
	DRV_ADC_CHANNEL_SENSE2,
	DRV_ADC_CHANNEL_SENSE3,
	DRV_ADC_CHANNEL_SENSE4,
	DRV_ADC_CHANNEL_SENSE5,
	DRV_ADC_CHANNEL_SENSE6,
	// Reads current sense diagnostic from HSD
	DRV_ADC_CHANNEL_ISENSE,
	
	DRV_ADC_CHANNEL_COUNT
};
