#pragma once

#include "config.h"

enum drv_adc_channel {
#if GENERAL_PURPOSE
	DRV_ADC_CHANNEL_VIOUT1 = 0,
	DRV_ADC_CHANNEL_ACCEL_X,
	DRV_ADC_CHANNEL_ACCEL_Y,
	DRV_ADC_CHANNEL_ACCEL_Z,
	DRV_ADC_CHANNEL_VIOUT2,
	DRV_ADC_CHANNEL_SENSE2,
	DRV_ADC_CHANNEL_VIOUT3,
	DRV_ADC_CHANNEL_SENSE3,
	DRV_ADC_CHANNEL_VIOUT4,
	DRV_ADC_CHANNEL_SENSE4,
	DRV_ADC_CHANNEL_VIOUT5,
	DRV_ADC_CHANNEL_SENSE5,
	DRV_ADC_CHANNEL_VIOUT6,
	DRV_ADC_CHANNEL_SENSE6,
#elif UPRIGHT
	DRV_ADC_CHANNEL_BRK_PWR_SENSE = 0,
	DRV_ADC_CHANNEL_BRK_TMP,
	DRV_ADC_CHANNEL_WHL_PWR_SENSE,
	DRV_ADC_CHANNEL_ACCEL_X,
	DRV_ADC_CHANNEL_ACCEL_Y,
#endif
	
	DRV_ADC_CHANNEL_COUNT
};
