#pragma once

enum drv_adc_channel {
	DRV_ADC_CHANNEL_VIOUT1,
	DRV_ADC_CHANNEL_ACCEL_X,
	DRV_ADC_CHANNEL_ACCEL_Y,
	DRV_ADC_CHANNEL_ACCEL_Z,
	DRV_ADC_CHANNEL_VIOUT2,
	DRV_ADC_CHANNEL_SENSE2,
	DRV_ADC_CHANNEL_VIOUT3,
	DRV_ADC_CHANNEL_SENSE3,
	DRV_ADC_CHANNEL_VIOUT4,
	DRV_ADC_CHANNEL_SENSE4,
	DRV_ADC_CHANNEL_VIOUT5,
	DRV_ADC_CHANNEL_SENSE5,
	DRV_ADC_CHANNEL_VIOUT6,
	DRV_ADC_CHANNEL_SENSE6,
	
	DRV_ADC_CHANNEL_COUNT
};